name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      run_tests:
        required: false
        type: boolean
        default: true
    outputs:
      test_result:
        description: "Test result"
        value: ${{ jobs.build.outputs.result }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - run: pip install -r requirements.txt

      - name: Run App
        run: |
          python app.py &
          sleep 5

      - name: Run Tests
        if: ${{ inputs.run_tests }}
        run: pytest

      - name: Set Output
        id: set-result
        run: echo "result=passed" >> $GITHUB_OUTPUT