name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
    outputs:
      image_url:
        value: ${{ jobs.docker.outputs.image }}

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.docker_token }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ inputs.image_name }}:${{ inputs.tag }} .

      - name: Push Image
        run: docker push ${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Set Output
        id: set-image
        run: echo "image=${{ inputs.image_name }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT